name: '${name}'
version: '${version}'
main: it.novaverse.weschematiccloud.WESchematicCloud
loader: it.novaverse.weschematiccloud.WESchematicCloudLoader
api-version: '1.20'
load: STARTUP
dependencies:
  server:
    WorldEdit: {}
